[workspace]
members = [
    "examples/simple",
    "examples/gradle"
]
resolver = "2"

[package]
name = "android-bindings"
version = "0.1.0"
edition = "2024"


[build-dependencies]
jbindgen = "0.1.0"
javac = "0.1"

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.22", features = ["invocation"] }
jni-macros = "0.22"
android-activity = { version = "0.6", features = ["native-activity"] }
ndk-context = "0.1.1"
jbindgen-annotations = "0.1.0"

[patch.crates-io]
jbindgen = { path = "../jbindgen/jbindgen/" }
