[package]
name = "gradle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.22", features = ["invocation"] }
log = "0.4.14"
ndk-context = "0.1.1"
android_logger = "0.15.0"
android-bindings = { path = "../../" }
